### ISSUE TITLE
ISO vs. POSIX C library

### ISSUE THREAD

**Issue by yguclu** [mattip/pycon2017_cffi#2]
Function `clock_gettime` and constant definition `CLOCK_PROCESS_CPUTIME_ID` in file **main.c** are not part of the C standard library, but come from the POSIX C library. In order to avoid compilation problems on some (unlucky) machines, I suggest to avoid them.

**Comment by mattip** [comment]
I put the timing in a `#ifdef` clause, could you check that it now works for you?
